name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.4.4
  - pip=22.1.2
  - pandas-profiling=3.2.0
  - pyarrow=8.0.0
  - ipywidgets
  - pip:
      - ipykernel==5.3.4